### ISSUE TITLE
Congratulations and question

### ISSUE THREAD

**Issue by frederikhors** [mfcochauxlaberge/jsonapi#107]
I discovered this project today from the jsonapi website.

Thanks for your job well done!

Just one question: if I start a project with this, can I be sure it won't be abandoned?

**Comment by frederikhors** [comment]
It would be great if we could create a real project (like https://github.com/gothinkster/realworld) by also agreeing together a JS client library if not server-rendered in Go.

And I'd also like to use [clean architecture](https://github.com/bxcodec/go-clean-arch).

**Comment by mfcochauxlaberge** [comment]
> It would be great if we could create a real project (like https://github.com/gothinkster/realworld) by also agreeing together a JS client library if not server-rendered in Go.

This is not something I planned to do for now, but anyone is free to give it a go.

> And I'd also like to use clean architecture.

Are you talking about refactoring this library so that it fits the clean architecture? This is a library, not a framework. It can be part of a system to follows this convention. If not, let me know what I can do to improve it.

To answer your first question, I can only say that for now I don't intend on abandoning this project. But you can't be sure it won't be abandoned. That is true for pretty much all projects to a certain extent.

**Comment by frederikhors** [comment]
> Are you talking about refactoring this library so that it fits the clean architecture?

Nope. I was referring to the demo that I hope to write together with those who want it.

**Comment by mfcochauxlaberge** [comment]
> > Are you talking about refactoring this library so that it fits the clean architecture?
> 
> Nope. I was referring to the demo that I hope to write together with those who want it.

Ah, in that case, I suppose whoever wants to build the demo can choose the architecture.
