### ISSUE TITLE
Use of UnmarshalDocument for patch requests

### ISSUE THREAD

**Issue by teleclimber** [mfcochauxlaberge/jsonapi#119]
Hi, 

I am working on a handler to update a resource. This is one of those where an attribute is being changed, and the request json includes only that attribute in the resource data (the other attributes are assumed unchanged, as allowed by the spec).

The problem is after I `UnmarshalDocument` I have no way to know what attributes were included in the request and which are not (because the returned resource is a Wrapper for the type, which includes all attributes).

I could check for zero-values of each attribute but this is error-prone because a zero-value could be a valid value.

What am I missing here? What is the right way to handle updates of a subset of attributes of a resource? Is there a way for Document to tell me which attributes are actually set and which are "undefined"?

Thanks.

**Comment by teleclimber** [comment]
After thinking a bit about this, it seems like the `Resource` interface could be tweaked a bit to resolve this: either add an `IsSet(key string) bool` method, or change the signature of Get to `Get(key string) (val interface{}, ok bool)`, which is consistent with how Go maps work, etc...

**Comment by mfcochauxlaberge** [comment]
I think this is what you are looking for: https://github.com/mfcochauxlaberge/jsonapi/blob/55e8c28b88cac9160d4af925e2193ab4d5ff45e9/resource.go#L218

Let me know if it isn't the case.

**Comment by mfcochauxlaberge** [comment]
Also, I couldn't implement something like `isSet` because all fields on a resource are always set. The default value can be up to the implementation I suppose, but there needs to be something. The concept of a field that may not be set might exist in a JavaScript objet or a Go `map`, but it isn't compatible with the JSON:API specification as far as I know.

In `UnmarshalPartialResource`, I make it clear that this will return a `Resource` (`SoftResource` in this case to be exact) of a temporary type that is a subset of the real type. But even in this case, the absent fields are totally absent from the type, not just "not set yet".

**Comment by teleclimber** [comment]
> The concept of a field that may not be set might exist in a JavaScript object or a Go map, but it isn't compatible with the JSON:API specification as far as I know.

The JSON:API spec gives an example of when this might be used: for updates to one or some attributes of a resource.

> "If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. The server MUST NOT interpret missing attributes as null values."

See [here](https://jsonapi.org/format/#crud-updating-resource-attributes).

`SoftResource` appears to be the intended solution, I'll try using that and will report back.

**Comment by mfcochauxlaberge** [comment]
Yeah, we agree.

I interpret the JSON:API differently. In a PATCH requests, the missing fields still exist and are part of the type. It's just that the values are considered to be what they are in the database since they are not in the payload. In the implement, I have to make a partial type.

But in practice it's the same thing and we agree.

Feel free to reopen if you believe `UnmarshalPartialResource` isn't quite the right answer.
