### ISSUE TITLE
Is there a plan to support repositories, routing, forwarding etc?

### ISSUE THREAD

**Issue by challarao** [mfcochauxlaberge/jsonapi#96]
Hi author,

This is the only active JSON:API project in golang. Others are dormant. Thanks for creating this.

I'm wondering if there is a plan to create features such as:
1. Repositories and routers
2. Automatic forwarding of relationships to other repositories based on type and id(and based on include parameter)

I'm basically looking for something along the lines of(Java) https://www.crnk.io/releases/stable/documentation/.

But at least routing support would be a good start. 

Thanks

PS: Unfortunately, it's not very easy to find libraries in golang that are active (whose git log shows recent commits)

**Comment by mfcochauxlaberge** [comment]
> This is the only active JSON:API project in golang.

The reason is was created. ;)

I read a bit of Crnk's documentation (I'm unfamiliar with it) and I'm not sure how I would translate some of those concepts to my library written in Go. It's meant to be more "flat".

Also, it's mostly a library, not a service. It's meant to hold a JSON:API schema which is used to parse and validate incoming requests. It can also marshal documents for the response. There are some tools that are more advanced, like an in-memory store that can be queried (including sorting, filtering, and pagination), but it's for demos and tests. Not suitable for production.

I did try another project (https://github.com/mfcochauxlaberge/karigo) that would use this library to build a service for running an API with a router, database transactions, etc, but I think I made some design mistakes and would like to rewrite it from scratch. This library is still maintained though.

Here's an idea for a quick router: 

You can make a `jsonapi.Schema` that contains all the schema information and makes sure everything is valid and consistent. You can give it manually made objects like `jsonapi.Type` and `jsonapi.Attr`, or you can give it a struct which will be reflected. This is cleaner and faster for the developer.

You could have such an interface: 

```
type TypeHandler interface {
	Get(jsonapi.URL, jsonapi.Document) jsonapi.Document
	Post(jsonapi.URL, jsonapi.Document) jsonapi.Document
	Update(jsonapi.URL, jsonapi.Document) jsonapi.Document
	Delete(jsonapi.URL, jsonapi.Document) jsonapi.Document
}

Also note that when you parse a URL and body from an `http.Request`, you get a `jsonapi.URL` object among other things.

```
type URL struct {
	// URL
	Fragments []string // [users, u1, articles]
	Route     string   // /users/:id/articles

	// Data
	IsCol           bool
	ResType         string
	ResID           string
	RelKind         string
	Rel             Rel
	BelongsToFilter BelongsToFilter

	// Params
	Params *Params
}
```

The `Fragments` are three strings that represent the path split in multiple parts. (side note: since it is validated from the schema, you can always be sure the whole object contain valid data). You _could_ have a router that accepts everything (not endpoints configured) and all requests are parsed with this library in a middleware. Then, all requests that don't make sense (type does not exist, invalid path, etc) would return an error and the request would not go further. Then, in your single handler, you have these `jsonapi.URL` and `jsonapi.Document` which are validated and ready to be played with. You _could_ do something like building an SQL query (or many) and shove the response in another `jsonapi.Document` to be returned to the client.

**Comment by mfcochauxlaberge** [comment]
> This is the only active JSON:API project in golang.

The reason is was created. ;)

I read a bit of Crnk's documentation (I'm unfamiliar with it) and I'm not sure how I would translate some of those concepts to my library written in Go. It's meant to be more "flat".

Also, it's mostly a library, not a service. It's meant to hold a JSON:API schema which is used to parse and validate incoming requests. It can also marshal documents for the response. There are some tools that are more advanced, like an in-memory store that can be queried (including sorting, filtering, and pagination), but it's for demos and tests. Not suitable for production.

I did try another project (https://github.com/mfcochauxlaberge/karigo) that would use this library to build a service for running an API with a router, database transactions, etc, but I think I made some design mistakes and would like to rewrite it from scratch. This library is still maintained though.

If you have an idea of how a simple and powerful router that would integrate this library well could work, feel free to inspire me. ;)

Also note that this library can parse an `http.Request` and return a `jsonapi.URL` and `jsonapi.Document`, validated from a `jsonapi.Schema`.

Let me know if I can give you more details.

**Comment by challarao** [comment]
Hi @mfcochauxlaberge,

Thanks for responding. Yeah, I was basically looking for a service. Something like karigo even if it doesn't support features supported by CRNK. That should be fine.

**Comment by challarao** [comment]
@mfcochauxlaberge Is it possible to have id as non-string type? (without implementing Resource interface)

**Comment by mfcochauxlaberge** [comment]
No, only string is supported to follow the spec:

> Every resource object MUST contain an id member and a type member. The values of the id and type members MUST be strings.

So adding support for an ID of type `int` wouldn't give many benefits. The library would still need to read from a string (JSON payload) and convert to a string when marshaling, so no performance gain.

Validation can be useful, but your IDs are probably generated on the backend, so assuming integers is okay. You can simply convert them to strings.

If you give me details on what kind of int support you need and how it would make sense to have it implemented, I can try to think more about it.

**Comment by challarao** [comment]
@mfcochauxlaberge My impression is that JSON:API says that from an external point of view(final output). I think it says that to avoid serializing an integer without quotes (id: 1 vs id:"1"). I don't think that should be a reason for not having a type of UUID etc as part of the structs. The serializer should make sure to serialize every id as a string.

**Comment by mfcochauxlaberge** [comment]
@challarao You're right, the specification cares about the final output, which is a string. Internally, you can go with pretty much anything you want, since you can always represent it as a string when the time comes to marshal.

But this library is exactly meant to be at the edge (marshaling and unmarshaling), so it has to deal with strings.

If you want a number or a UUID, you absolutely can. You simply need to implement the interface. But when implementing the `GetID` method, you will need to convert to a string and return it. There is not much I could do to fix that, since strings are used for IDs in the specification.

I also think the benefits of supporting other types are very small and would bring in some complexity to the library.

**Comment by teleclimber** [comment]
@challarao if you're still looking for a router I am experimenting with something here: https://github.com/teleclimber/jsonapirouter

@mfcochauxlaberge I'd be interested in your thoughts on my approach (if you can make sense of it 😅)
